"""initial schema

Revision ID: 7dfe001e88c4
Revises: 
Create Date: 2026-08-18 10:56:36.713607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfe001e88c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('operator', 'supervisor', 'management', name='user_role'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('part_replacements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('part_name', sa.String(length=255), nullable=False),
    sa.Column('replaced_at', sa.Date(), nullable=False),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('downtime_minutes', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('cleaning', 'oiling', 'part_replacement', 'repair', name='task_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_interval_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'overdue', name='task_status'), server_default='pending', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rescheduled_by', sa.UUID(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rescheduled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_instances')
    op.drop_table('task_types')
    op.drop_table('repair_logs')
    op.drop_table('part_replacements')
    op.drop_table('users')
    op.drop_table('machines')
    # ### end Alembic commands ###
    # Alembic's autogenerate doesn't emit DROP TYPE for Postgres native enums on
    # drop_table, so without this a downgrade->upgrade cycle fails with
    # DuplicateObject on the next CREATE TYPE.
    sa.Enum(name='task_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='task_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
